name: Rankify CI

on:
  workflow_dispatch: # Manual trigger
  pull_request:
    types: [opened, review_requested, synchronize]
    branches:
      - main

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  ci_job:
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: mongodb://ci-username:ci-password@localhost:27017/rankify-ci?authSource=admin

    steps:
      - uses: actions/checkout@v3

        # https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#github-actions
      #   - name: Cache dependencies
      #     uses: actions/cache@v4
      #     with:
      #       path: |
      #         ~/.npm
      #         ${{ github.workspace }}/.next/cache
      #       key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
      #       restore-keys: |
      #         ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Setup Node 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run ts-check
        run: npm run ts-check

      - name: Start MongoDB 7
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 7
          mongodb-username: ci-username
          mongodb-password: ci-password
          mongodb-db: rankify-ci

      - name: Run tests
        run: npm run test

      - name: Run build
        run: npm run build
